version: "3.8"

services:
  app:
    build: .
    command: ["./main"]
    ports:
      - "9090:9090"
    volumes:
      - .:/app
      - /etc/letsencrypt/live/40-85-136-203.nip.io:/etc/letsencrypt/live/40-85-136-203.nip.io
      - /etc/letsencrypt/archive/40-85-136-203.nip.io:/etc/letsencrypt/archive/40-85-136-203.nip.io
    environment:
      - DATABASE_PATH=/app/data/whoknows.db
