version: "3.8"

services:
  sqlite:
    image: nouchka/sqlite3:latest # SQLite image
    container_name: sqlite_container
    volumes:
      - ./data:/data
    entrypoint: ["sqlite3"]
    command: ["/data/your-database.db"]
