name: Restrict PRs to Main from Dev

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.event.pull_request.head.ref != 'dev'
        run: |
          echo "Pull requests to main can only be created from dev."
          exit 1
