name: Notify Discord on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          JSON_PAYLOAD=$(jq -n --arg commit "${{ github.event.head_commit.message }}" --arg actor "${{ github.actor }}" '{
            "content": null,
            "embeds": [
              {
                "title": "New PR merged",
                "description": ("🚀 A new commit has been merged into **main**!\nCommit: **" + $commit + "**\nBy: **" + $actor + "**"),
                "color": 5814783,
                "author": {
                  "name": ("Actor: " + $actor)
                }
              }
            ],
            "attachments": []
          }')

          curl -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" ${{ secrets.DISCORD_WEBHOOK }}

#https://discord.com/api/webhooks/1334893857111933020/b3-KM9quIbtIQYomIhPMRi_UJVf4uezHSYhloEIQqUMRjuWKOaq98BSm4TlI7lzOJFyY
