name: Notify Discord on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "content": null,
              "embeds": [
                {
                  "title": "New PR merged",
                  "description": "🚀 A new commit has been merged into **main**!\nCommit: **${{ github.event.head_commit.message }}**\nBy: **${{ github.actor }}**",
                  "color": 5814783,
                  "author": {
                    "name": "Actor: ${{ github.actor }}"
                  }
                }
              ],
              "attachments": []
            }' \
            ${{ secrets.DISCORD_WEBHOOK }}

#https://discord.com/api/webhooks/1334893857111933020/b3-KM9quIbtIQYomIhPMRi_UJVf4uezHSYhloEIQqUMRjuWKOaq98BSm4TlI7lzOJFyY
